//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingGettingPropertyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAssessment
    {
        public int Account_Number { get; set; }
        public string Address { get; set; }
        public string Unit { get; set; }
        public string Homestead_Exemption { get; set; }
        public string Property_Category { get; set; }
        public string Property_Type { get; set; }
        public Nullable<int> Market_Value { get; set; }
        public Nullable<int> Taxable_Land { get; set; }
        public Nullable<int> Taxable_Building { get; set; }
        public Nullable<int> Exempt_Land { get; set; }
        public Nullable<int> Exempt_Building { get; set; }
        public Nullable<float> Longitude { get; set; }
        public Nullable<float> Latitude { get; set; }
        public string AcctNumStr { get; set; }
    }
}
