//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingGettingPropertyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyData
    {
        public int Account_Number { get; set; }
        public string Status { get; set; }
        public string results { get; set; }
        public string AcctNumStr { get; set; }
    }
}
